# Generated by Django 5.1.1 on 2024-09-24 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('Estágio', 'Estágio'), ('Projeto de Pesquisa', 'Projeto de Pesquisa'), ('Projeto de Extensão', 'Projeto de Extensão'), ('Emprego', 'Emprego')], max_length=50)),
                ('descricao', models.TextField()),
                ('requisitos', models.TextField()),
                ('localizacao', models.CharField(max_length=255)),
                ('carga_horaria', models.IntegerField()),
                ('remuneracao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('numero_vagas', models.IntegerField()),
                ('anexos', models.FileField(blank=True, null=True, upload_to='anexos/')),
                ('forma_selecao', models.CharField(max_length=255)),
                ('categoria_tags', models.CharField(max_length=255)),
                ('cursos_desejados', models.CharField(max_length=255)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='empresas.empresa')),
            ],
        ),
    ]
